### ISSUE TITLE
The mod dosent work with amd graphics cards

### ISSUE THREAD

**Issue by Kratus21** [RuffleSteels/Jebbed-Out#3]
me and some friends of mine cant even start the mod alone and we have amd graphics cards however the friends of mine with an Nvdia graphics card dont have any issues

**Comment by Poopooracoocoo** [comment]
[latest.log](https://github.com/user-attachments/files/17804654/latest.log)

<details><summary>Details</summary>

```
[05:08:15] [main/INFO]: Loading Minecraft 1.21.1 with Fabric Loader 0.16.9
[05:08:16] [main/INFO]: Loading 56 mods:
	- fabric-api 0.108.0+1.21.1
	   |-- fabric-api-base 0.4.42+6573ed8c19
	   |-- fabric-api-lookup-api-v1 1.6.70+b559734419
	   |-- fabric-biome-api-v1 13.0.30+be1ed2d719
	   |-- fabric-block-api-v1 1.0.22+0af3f5a719
	   |-- fabric-block-view-api-v2 1.0.10+6573ed8c19
	   |-- fabric-blockrenderlayer-v1 1.1.52+0af3f5a719
	   |-- fabric-client-tags-api-v1 1.1.15+6573ed8c19
	   |-- fabric-command-api-v1 1.2.49+f71b366f19
	   |-- fabric-command-api-v2 2.2.28+6ced4dd919
	   |-- fabric-commands-v0 0.2.66+df3654b319
	   |-- fabric-content-registries-v0 8.0.18+b559734419
	   |-- fabric-convention-tags-v1 2.1.2+7f945d5b19
	   |-- fabric-convention-tags-v2 2.9.2+e60e56d419
	   |-- fabric-crash-report-info-v1 0.2.29+0af3f5a719
	   |-- fabric-data-attachment-api-v1 1.3.0+8e331c5719
	   |-- fabric-data-generation-api-v1 20.2.23+16c4ae2519
	   |-- fabric-dimensions-v1 4.0.0+6fc22b9919
	   |-- fabric-entity-events-v1 1.7.0+2122d82819
	   |-- fabric-events-interaction-v0 0.7.13+ba9dae0619
	   |-- fabric-game-rule-api-v1 1.0.53+6ced4dd919
	   |-- fabric-item-api-v1 11.1.1+d5debaed19
	   |-- fabric-item-group-api-v1 4.1.6+6823f7cd19
	   |-- fabric-key-binding-api-v1 1.0.47+0af3f5a719
	   |-- fabric-keybindings-v0 0.2.45+df3654b319
	   |-- fabric-lifecycle-events-v1 2.5.0+01d9a51c19
	   |-- fabric-loot-api-v2 3.0.15+3f89f5a519
	   |-- fabric-loot-api-v3 1.0.3+3f89f5a519
	   |-- fabric-message-api-v1 6.0.13+6573ed8c19
	   |-- fabric-model-loading-api-v1 2.0.0+fe474d6b19
	   |-- fabric-networking-api-v1 4.3.0+c7469b2119
	   |-- fabric-object-builder-api-v1 15.2.1+40875a9319
	   |-- fabric-particles-v1 4.0.2+6573ed8c19
	   |-- fabric-recipe-api-v1 5.0.13+6508971219
	   |-- fabric-registry-sync-v0 5.1.3+60c3209b19
	   |-- fabric-renderer-api-v1 3.4.0+c705a49c19
	   |-- fabric-renderer-indigo 1.7.0+c705a49c19
	   |-- fabric-renderer-registries-v1 3.2.68+df3654b319
	   |-- fabric-rendering-data-attachment-v1 0.3.48+73761d2e19
	   |-- fabric-rendering-fluids-v1 3.1.6+1daea21519
	   |-- fabric-rendering-v0 1.1.71+df3654b319
	   |-- fabric-rendering-v1 5.0.5+df16efd019
	   |-- fabric-resource-conditions-api-v1 4.3.0+8dc279b119
	   |-- fabric-resource-loader-v0 1.3.1+5b5275af19
	   |-- fabric-screen-api-v1 2.0.25+8b68f1c719
	   |-- fabric-screen-handler-api-v1 1.3.87+b559734419
	   |-- fabric-sound-api-v1 1.0.23+6573ed8c19
	   |-- fabric-transfer-api-v1 5.4.2+95bead5f19
	   \-- fabric-transitive-access-wideners-v1 6.1.0+1daea21519
	- fabricloader 0.16.9
	   \-- mixinextras 0.4.1
	- java 21
	- jebbed 1.0
	   |-- mixinextras 0.4.1
	   |-- org_apache_commons_commons-collections4 4.5.0-M2
	   \-- placeholder-api 2.4.0+1.21
	- minecraft 1.21.1
[05:08:16] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.7 Source=file:/C:/Users/anon/AppData/Roaming/PrismLauncher/libraries/net/fabricmc/sponge-mixin/0.15.4+mixin.0.8.7/sponge-mixin-0.15.4+mixin.0.8.7.jar Service=Knot/Fabric Env=CLIENT
[05:08:16] [main/INFO]: Compatibility level set to JAVA_17
[05:08:16] [main/INFO]: Compatibility level set to JAVA_21
[05:08:17] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.4.1).
[05:08:17] [Datafixer Bootstrap/INFO]: 226 Datafixer optimizations took 338 milliseconds
[05:08:18] [main/WARN]: Invalid registry value type detected for PerfOS counters. Should be REG_DWORD. Ignoring: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PerfOS\Performance\Disable Performance Counters.
[05:08:21] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[05:08:21] [Render thread/INFO]: Setting user: anon
[05:08:21] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[05:08:21] [Render thread/INFO]: Backend library: LWJGL version 3.3.3-snapshot
[05:08:22] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, jebbed, placeholder-api
[05:08:22] [Worker-Main-8/INFO]: Found unifont_all_no_pua-15.1.05.hex, loading
[05:08:22] [Worker-Main-4/INFO]: Found unifont_jp_patch-15.1.05.hex, loading
[05:08:23] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[05:08:23] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[05:08:23] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Realtek HD Audio 2nd output (Realtek(R) Audio)
[05:08:23] [Render thread/INFO]: Sound engine started
[05:08:23] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[05:08:23] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[05:08:23] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[05:08:23] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[05:08:23] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[05:08:23] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[05:08:23] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[05:08:23] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[05:08:23] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[05:08:24] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[05:08:24] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/paintings.png-atlas
[05:08:24] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[05:08:24] [Render thread/INFO]: Created: 64x64x0 minecraft:textures/atlas/map_decorations.png-atlas
[05:08:24] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[05:08:24] [Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.RuntimeException: could not reload shaders
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:722) ~[?:?]
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at knot/net.minecraft.class_4014.method_18365(class_4014.java:69) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_18859(class_1255.java:162) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_16075(class_1255.java:136) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_1255.method_5383(class_1255.java:121) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1523(class_310.java:1240) [client-intermediary.jar:?]
	at knot/net.minecraft.class_310.method_1514(class_310.java:882) [client-intermediary.jar:?]
	at knot/net.minecraft.client.main.Main.main(Main.java:256) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.16.9.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:105) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) [NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) [NewLaunch.jar:?]
Caused by: java.lang.RuntimeException: could not reload shaders
	at knot/net.minecraft.class_757.method_34538(class_757.java:537) [client-intermediary.jar:?]
	at knot/net.minecraft.class_757$1.method_45777(class_757.java:419) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757$1.method_18788(class_757.java:396) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 15 more
Caused by: net.minecraft.class_2973: Invalid shaders/core/jebbed/rendertype_custom_tint.json: Couldn't compile fragment program (jebbed, jebbed/rendertype_custom_tint) : ERROR: 0:59: '' : float literal needs a decimal point or exponent 
ERROR: 0:59: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.
	at knot/net.minecraft.class_2973.method_12856(class_2973.java:48) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_5944.<init>(class_5944.java:172) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.modifyReceiver$znn000$jebbed$addShaderPrograms(class_757.java:3072) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_34538(class_757.java:478) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757$1.method_45777(class_757.java:419) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757$1.method_18788(class_757.java:396) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 15 more
Caused by: java.io.IOException: Couldn't compile fragment program (jebbed, jebbed/rendertype_custom_tint) : ERROR: 0:59: '' : float literal needs a decimal point or exponent 
ERROR: 0:59: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.
	at knot/net.minecraft.class_281.method_34416(class_281.java:69) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_281.method_1283(class_281.java:51) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_5944.method_34579(class_5944.java:210) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_5944.<init>(class_5944.java:158) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.modifyReceiver$znn000$jebbed$addShaderPrograms(class_757.java:3072) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757.method_34538(class_757.java:478) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757$1.method_45777(class_757.java:419) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_757$1.method_18788(class_757.java:396) ~[client-intermediary.jar:?]
	at knot/net.minecraft.class_4080.method_18790(class_4080.java:13) ~[client-intermediary.jar:?]
	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	... 15 more
[05:08:24] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, jebbed, placeholder-api
[05:08:24] [Worker-Main-8/INFO]: Found unifont_all_no_pua-15.1.05.hex, loading
[05:08:24] [Worker-Main-4/INFO]: Found unifont_jp_patch-15.1.05.hex, loading
[05:08:24] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[05:08:24] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[05:08:24] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Realtek HD Audio 2nd output (Realtek(R) Audio)
[05:08:24] [Render thread/INFO]: Sound engine started
[05:08:24] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[05:08:24] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[05:08:24] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[05:08:24] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[05:08:24] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[05:08:24] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[05:08:24] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[05:08:24] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[05:08:24] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[05:08:24] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[05:08:24] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/paintings.png-atlas
[05:08:24] [Render thread/INFO]: Created: 256x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[05:08:24] [Render thread/INFO]: Created: 64x64x0 minecraft:textures/atlas/map_decorations.png-atlas
[05:08:24] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
``` 

</details>

**Comment by foxt** [comment]
+1 with Apple GPUs too.

```
jebbed/rendertype_custom_tint.fsh: jebbed/rendertype_custom_tint.fsh: ERROR: 0:59: 'f': syntax error: syntax error
```
